<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Lenovo-PC" ignored="0" name="Default test" tests="4" failures="3" timestamp="2021-10-12T16:09:34 IST" time="4.549" errors="0">
  <testcase name="BusStopLocationFind" time="4.066" classname="FindBusStopLocation.json2Pojo"/>
  <testcase name="StopsResponseValidation" time="0.369" classname="FindBusStopLocation.json2Pojo">
    <failure type="java.lang.AssertionError" message="
Expected: is [&amp;quot;400324&amp;quot;, &amp;quot;SW&amp;quot;, &amp;quot;MTA_400324&amp;quot;, &amp;quot;40.747494&amp;quot;, &amp;quot;0&amp;quot;, &amp;quot;-73.985338&amp;quot;, &amp;quot;5 AV/W 33 ST&amp;quot;, &amp;quot;UNKNOWN&amp;quot;]
     but: was [&amp;quot;400323&amp;quot;, &amp;quot;SW&amp;quot;, &amp;quot;MTA_400323&amp;quot;, &amp;quot;40.749477&amp;quot;, &amp;quot;0&amp;quot;, &amp;quot;-73.983921&amp;quot;, &amp;quot;5 AV/W 35 ST&amp;quot;, &amp;quot;UNKNOWN&amp;quot;]">
      <![CDATA[java.lang.AssertionError: 
Expected: is ["400324", "SW", "MTA_400324", "40.747494", "0", "-73.985338", "5 AV/W 33 ST", "UNKNOWN"]
     but: was ["400323", "SW", "MTA_400323", "40.749477", "0", "-73.983921", "5 AV/W 35 ST", "UNKNOWN"]
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at FindBusStopLocation.json2Pojo.StopsResponseValidation(json2Pojo.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- StopsResponseValidation -->
  <testcase name="agencyResponseValiatio" time="0.035" classname="FindBusStopLocation.json2Pojo">
    <failure type="java.lang.AssertionError" message="
Expected: is [&amp;quot;&amp;quot;, &amp;quot;&amp;quot;, &amp;quot;en&amp;quot;, &amp;quot;MTA New York City Transit&amp;quot;, &amp;quot;718-330-1234&amp;quot;, &amp;quot;false&amp;quot;, &amp;quot;America/New_York&amp;quot;, &amp;quot;http://www.mta.info&amp;quot;]
     but: was [&amp;quot;&amp;quot;, &amp;quot;&amp;quot;, &amp;quot;EN&amp;quot;, &amp;quot;MTA Bus Company&amp;quot;, &amp;quot;&amp;quot;, &amp;quot;false&amp;quot;, &amp;quot;America/New_York&amp;quot;, &amp;quot;http://www.mta.info&amp;quot;]">
      <![CDATA[java.lang.AssertionError: 
Expected: is ["", "", "en", "MTA New York City Transit", "718-330-1234", "false", "America/New_York", "http://www.mta.info"]
     but: was ["", "", "EN", "MTA Bus Company", "", "false", "America/New_York", "http://www.mta.info"]
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at FindBusStopLocation.json2Pojo.agencyResponseValiatio(json2Pojo.java:135)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- agencyResponseValiatio -->
  <testcase name="routesResponseValiatio" time="0.002" classname="FindBusStopLocation.json2Pojo">
    <failure type="java.lang.AssertionError" message="
Expected: is [&amp;quot;EE352E&amp;quot;, &amp;quot;via 5th Av / Madison Av&amp;quot;, &amp;quot;MTA NYCT_M1&amp;quot;, &amp;quot;Harlem - East Village&amp;quot;, &amp;quot;M1&amp;quot;, &amp;quot;FFFFFF&amp;quot;, &amp;quot;3&amp;quot;, &amp;quot;&amp;quot;]
     but: was [&amp;quot;B933AD&amp;quot;, &amp;quot;via 5th Av / Madison Av / AC Powell Blvd&amp;quot;, &amp;quot;MTA NYCT_M2&amp;quot;, &amp;quot;Washington Heights - East Village&amp;quot;, &amp;quot;M2&amp;quot;, &amp;quot;FFFFFF&amp;quot;, &amp;quot;3&amp;quot;, &amp;quot;&amp;quot;]">
      <![CDATA[java.lang.AssertionError: 
Expected: is ["EE352E", "via 5th Av / Madison Av", "MTA NYCT_M1", "Harlem - East Village", "M1", "FFFFFF", "3", ""]
     but: was ["B933AD", "via 5th Av / Madison Av / AC Powell Blvd", "MTA NYCT_M2", "Washington Heights - East Village", "M2", "FFFFFF", "3", ""]
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at FindBusStopLocation.json2Pojo.routesResponseValiatio(json2Pojo.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- routesResponseValiatio -->
</testsuite> <!-- Default test -->
